site_name: IT Support Knowledge Base
theme:
  name: material

nav:
  - Home: index.md
  - Windows Issues:
      - Reset Forgotten Password: windows/reset-password.md
  - Browser Issues:
      - Clear Browser Cache: browser/clear-browser-cache.md
  - PowerShell Scripts:
      - Install Software via PowerShell: powershell/install-software.md